language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install:
  - pip install tox
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

python:
  - "3.5"

script:
  - tox
